### Importing the libraries

In [115]:
import numpy as Nupy
import pandas as Pada
import matplotlib as plt

### Importing the Dataset and setting X and y

In [116]:
dataset = Pada.read_csv("RealEstateDoto.csv")
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [117]:
print(X)

[[2450    4 2018]
 [ 850    1 2020]
 [1800    3 2015]
 [3200    5 2021]
 [1200    2 2010]
 [2100    3 1925]
 [1650    3 2022]
 [2800    4 1998]
 [ 450    0 2019]
 [5500    6 2017]
 [ 950    2 2008]
 [1450    2 2020]
 [2350    4 1890]
 [1100    2 2012]
 [ 800    1 2005]
 [1950    3 2016]
 [1300    2 1935]
 [2000    3 2023]
 [1750    3 2014]
 [ 750    1 2021]
 [2900    5 1985]
 [1050    1 2019]
 [2400    4 2013]
 [ 900    1 2020]
 [1600    3 2007]
 [2200    2 2018]
 [1900    3 2011]
 [2750    4 2009]
 [1100    2 2022]
 [1400    2 2003]]


In [118]:
print(y)

[ 750000  425000  520000 1250000  285000  680000  595000  465000  195000
 2100000  315000  485000  625000  890000  225000  545000  510000  625000
  475000  365000  715000  445000  580000  395000  425000  675000  535000
  695000  475000  385000]


### Training the Decision Tree regression model on the whole dataset

In [119]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X, y)

DecisionTreeRegressor(random_state=0)

### Predicting a New Result

In [120]:
SurfAr = input("Please enter the Surface Area")
BedR_nb = input("Please enter the bedroom number")
Yeah_r = input("Please enter the year of construction")

print(f"for a House with a Surface Area of {SurfAr}, {BedR_nb} bedrooms and built in {Yeah_r}, the prince would be : $",regressor.predict([[SurfAr,BedR_nb,Yeah_r]]))

for a House with a Surface Area of 2000, 4 bedrooms and built in 2018, the prince would be : $ [625000.]
